SET DATABASE SQL SYNTAX ORA TRUE
/

CREATE SEQUENCE ACCOUNT_ID_SEQ MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOCYCLE
/

CREATE TABLE ACCOUNT (
    ID NUMBER(19) NOT NULL,
    AMOUNT NUMBER(38, 8) NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID)
)
/
